# Generated by Django 3.2.9 on 2021-12-15 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EachDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.IntegerField()),
                ('month_name', models.CharField(max_length=64)),
                ('year_name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('position', models.IntegerField(choices=[(1, 'Instalator'), (2, 'Elektryk'), (3, 'Pracownik biurowy'), (4, 'Handlowiec')])),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('street_name', models.CharField(max_length=128)),
                ('city_name', models.CharField(max_length=128)),
                ('zip_code', models.CharField(max_length=10)),
                ('type_of_investment', models.IntegerField(choices=[(1, 'Panele fotowoltaiczne'), (2, 'Pompa ciepła'), (3, 'Kolektory słoneczne'), (4, 'Kocioł')])),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BRAK', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SquadInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management_app.employee')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.investment')),
                ('squad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management_app.squad')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentEachDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.eachdate')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.investment')),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='workers',
            field=models.ManyToManyField(through='management_app.SquadInvestment', to='management_app.Squad'),
        ),
        migrations.AddField(
            model_name='employee',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.squad'),
        ),
        migrations.AddField(
            model_name='eachdate',
            name='investment',
            field=models.ManyToManyField(through='management_app.InvestmentEachDate', to='management_app.Investment'),
        ),
    ]
