# Generated by Django 3.2.9 on 2021-12-12 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.investment')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.squad')),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='workers',
            field=models.ManyToManyField(through='management_app.SquadInvestment', to='management_app.Squad'),
        ),
    ]
