# Generated by Django 3.2.9 on 2021-12-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eachdate',
            name='month_name',
            field=models.IntegerField(),
        ),
    ]
