# Generated by Django 3.2.9 on 2021-12-14 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0004_squadinvestment_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='squad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management_app.squad'),
        ),
    ]
